config/routes.rb
Rails.application.routes.draw do
  resources :carros
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/carro.rb
class Carro < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carros_controller.rb
class CarrosController < ApplicationController
  before_action :set_carro, only: %i[ show edit update destroy ]

  # GET /carros or /carros.json
  def index
    @carros = Carro.all
  end

  # GET /carros/1 or /carros/1.json
  def show
  end

  # GET /carros/new
  def new
    @carro = Carro.new
  end

  # GET /carros/1/edit
  def edit
  end

  # POST /carros or /carros.json
  def create
    @carro = Carro.new(carro_params)

    respond_to do |format|
      if @carro.save
        format.html { redirect_to carro_url(@carro), notice: "Carro was successfully created." }
        format.json { render :show, status: :created, location: @carro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carros/1 or /carros/1.json
  def update
    respond_to do |format|
      if @carro.update(carro_params)
        format.html { redirect_to carro_url(@carro), notice: "Carro was successfully updated." }
        format.json { render :show, status: :ok, location: @carro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carros/1 or /carros/1.json
  def destroy
    @carro.destroy

    respond_to do |format|
      format.html { redirect_to carros_url, notice: "Carro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carro
      @carro = Carro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def carro_params
      params.require(:carro).permit(:hecho, :modelo, :año)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carros_helper.rb
module CarrosHelper
end

app/views/carros/_carro.html.erb
<div id="<%= dom_id carro %>">
  <p>
    <strong>Hecho:</strong>
    <%= carro.hecho %>
  </p>

  <p>
    <strong>Modelo:</strong>
    <%= carro.modelo %>
  </p>

  <p>
    <strong>Año:</strong>
    <%= carro.año %>
  </p>

</div>

app/views/carros/_form.html.erb
<%= form_with(model: carro) do |form| %>
  <% if carro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(carro.errors.count, "error") %> prohibited this carro from being saved:</h2>

      <ul>
        <% carro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :hecho, style: "display: block" %>
    <%= form.text_field :hecho %>
  </div>

  <div>
    <%= form.label :modelo, style: "display: block" %>
    <%= form.text_field :modelo %>
  </div>

  <div>
    <%= form.label :año, style: "display: block" %>
    <%= form.text_field :año %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carros/edit.html.erb
<h1>Editing carro</h1>

<%= render "form", carro: @carro %>

<br>

<div>
  <%= link_to "Show this carro", @carro %> |
  <%= link_to "Back to carros", carros_path %>
</div>

app/views/carros/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carros</h1>

<div id="carros">
  <% @carros.each do |carro| %>
    <%= render carro %>
    <p>
      <%= link_to "Show this carro", carro %>
    </p>
  <% end %>
</div>

<%= link_to "New carro", new_carro_path %>

app/views/carros/new.html.erb
<h1>New carro</h1>

<%= render "form", carro: @carro %>

<br>

<div>
  <%= link_to "Back to carros", carros_path %>
</div>

app/views/carros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @carro %>

<div>
  <%= link_to "Edit this carro", edit_carro_path(@carro) %> |
  <%= link_to "Back to carros", carros_path %>

  <%= button_to "Destroy this carro", @carro, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrimeraWebRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>